import assert from 'node:assert/strict';
import { mkdtemp, readFile, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { createGameApi } from './api.ts';
async function apiFor(fetch?: typeof globalThis.fetch, apiKey?: string) { const root = await mkdtemp(join(tmpdir(), 'chatjipiti-api-')); return createGameApi({ rootDir: root, generatedDir: join(root, '.generated'), fetch, apiKey }); }
async function call(api: ReturnType<typeof createGameApi>, path: string, init: RequestInit = {}) { const response = await api.handle(new Request(`http://localhost${path}`, init)); assert.ok(response); return response; }
function png1536x1024() { const bytes = Buffer.alloc(24); Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]).copy(bytes); bytes.writeUInt32BE(13, 8); bytes.write('IHDR', 12, 'ascii'); bytes.writeUInt32BE(1536, 16); bytes.writeUInt32BE(1024, 20); return bytes; }
test('reports missing configuration and rejects billable generation', async () => { const api = await apiFor(); assert.deepEqual(await (await call(api, '/api/status')).json(), { configured: false }); const response = await call(api, '/api/generate', { method: 'POST', body: JSON.stringify({ kind: 'cards', prompt: 'atlas' }) }); assert.equal(response.status, 503); assert.match((await response.json() as { error: string }).error, /OPENAI_API_KEY/); });
test('sets a valid local key once without returning it', async () => { const root = await mkdtemp(join(tmpdir(), 'chatjipiti-api-')); const api = createGameApi({ rootDir: root, generatedDir: join(root, '.generated') }); const key = 'sk-aaaaaaaaaaaaaaaaaaaa'; const response = await call(api, '/api/setup-key', { method: 'POST', body: JSON.stringify({ apiKey: key }) }); assert.equal(response.status, 201); assert.deepEqual(await response.json(), { configured: true }); assert.equal(await readFile(join(root, '.env.local'), 'utf8'), `OPENAI_API_KEY=${key}\n`); assert.equal((await stat(join(root, '.env.local'))).mode & 0o777, 0o600); assert.equal((await call(api, '/api/setup-key', { method: 'POST', body: JSON.stringify({ apiKey: key }) })).status, 409); });
test('validates request before an upstream call', async () => { let called = false; const api = await apiFor((async () => { called = true; return new Response(); }) as typeof fetch, 'sk_aaaaaaaaaaaaaaaaaaaa'); const response = await call(api, '/api/generate', { method: 'POST', body: JSON.stringify({ kind: 'nope', prompt: '' }) }); assert.equal(response.status, 400); assert.equal(called, false); });
test('stores mocked GPT Image output and exposes only a manifest asset', async () => { const png = png1536x1024(); const api = await apiFor((async (url, init) => { assert.equal(String(url), 'https://api.openai.com/v1/images/generations'); assert.equal((init?.headers as Headers).get('authorization'), 'Bearer sk_aaaaaaaaaaaaaaaaaaaa'); const payload = JSON.parse(String(init?.body)); assert.equal(payload.model, 'gpt-image-2.5-sunburst'); assert.equal(payload.size, '1536x1024'); return Response.json({ data: [{ b64_json: png.toString('base64') }] }); }) as typeof fetch, 'sk_aaaaaaaaaaaaaaaaaaaa'); const queued = await (await call(api, '/api/generate', { method: 'POST', body: JSON.stringify({ kind: 'cards', prompt: 'abstract agent icons' }) })).json() as { id: string; status: string }; assert.ok(queued.status === 'queued' || queued.status === 'running'); await api.whenIdle(); const done = await (await call(api, `/api/generations/${queued.id}`)).json() as { status: string; asset: { url: string } }; assert.equal(done.status, 'completed'); assert.deepEqual(Buffer.from(await (await call(api, done.asset.url)).arrayBuffer()), png); assert.equal((await call(api, '/api/generated/definitely-not-present.png')).status, 404); });
test('rejects non-PNG image payloads before persisting an asset', async () => { const api = await apiFor((async () => Response.json({ data: [{ b64_json: Buffer.from('not-a-png').toString('base64') }] })) as typeof fetch, 'sk_aaaaaaaaaaaaaaaaaaaa'); const queued = await (await call(api, '/api/generate', { method: 'POST', body: JSON.stringify({ kind: 'cards', prompt: 'abstract agent icons' }) })).json() as { id: string }; await api.whenIdle(); const failed = await (await call(api, `/api/generations/${queued.id}`)).json() as { status: string; error: string }; assert.equal(failed.status, 'failed'); assert.match(failed.error, /not a PNG/); assert.deepEqual(await (await call(api, '/api/assets')).json(), { assets: [] }); });
test('redacts API-shaped secrets from upstream image errors', async () => { const secret = 'sk_supersecret_abcdefghijklmnop'; const api = await apiFor((async () => Response.json({ error: { message: `request used ${secret}` } }, { status: 401 })) as typeof fetch, 'sk_aaaaaaaaaaaaaaaaaaaa'); const queued = await (await call(api, '/api/generate', { method: 'POST', body: JSON.stringify({ kind: 'cards', prompt: 'abstract agent icons' }) })).json() as { id: string }; await api.whenIdle(); const failed = await (await call(api, `/api/generations/${queued.id}`)).json() as { error: string }; assert.doesNotMatch(failed.error, /sk_supersecret/); assert.match(failed.error, /redacted API key/); });
